# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
defaultContentLanguage = "it"


disableLanguages = ['en']

enableRobotsTXT = true
paginate = 10
summaryLength = 10
googleAnalytics = "G-2LGG1T7GGB"

[outputs]
  home = ["HTML", "RSS", "JSON"]


