baseURL: https://codeandrun.it/
defaultContentLanguage: it
disableLanguages:
  - en
languageCode: it-it
enableRobotsTXT: true
pagination:
  paginate: 12
summaryLength: 100
theme: congo
timeout: 300s
rssLimit: 1000
disqusShortname: alexmufatti
googleAnalytics: G-2LGG1T7GGB
outputs:
  home:
    - HTML
    - RSS
    - JSON
