# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://codeandrun.it/"
defaultContentLanguage = "it"


disableLanguages = ['en']

enableRobotsTXT = true
paginate = 10
summaryLength = 10
googleAnalytics = "G-2LGG1T7GGB"
canonifyURLs = true
languageCode = 'it-it'
theme        = "congo"
timeout      = 300000
disqusShortname = "alexmufatti"

[outputs]
  home = ["HTML", "RSS", "JSON"]


