languageCode = "it"
languageName = "Italian"
weight = 1


[params]
isoCode = "it"
rtl = false
description = "Blog of a running developer"
displayName = "IT"
dateFormat = "2 January 2006"

title = "Code And Run"
# logo = "logo.png"
copyright = '<a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.'

[params.author]
  name = "Code And Run"
  image = "avatar.png"
  headline = "Blog of a running developer"
  bio = ""
  links = [
     { email = "mailto:alex@codeandrun.it" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
     { dev = "https://dev.to/alexmufatti" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/alexmufatti" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
     { hashnode = "https://codeandrun.hashnode.dev" },
     { instagram = "https://instagram.com/alexmufatti" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/amufatti" },
     { mastodon = "https://mastodon.uno/@alexmufatti" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
     { reddit = "https://reddit.com/user/alexmufatti" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
     { stack-overflow = "https://stackoverflow.com/users/606622/alex-mufatti" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
     { twitter = "https://twitter.com/alexmufatti" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
     { strava = "https://www.strava.com/athletes/12353579" },
   ]
