languageCode: it
languageName: Italian
weight: 1
copyright: '<a rel="license"
  href="https://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative
  Commons License" style="border-width:0"
  src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This
  work is licensed under a <a rel="license"
  href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons
  Attribution-ShareAlike 4.0 International License</a>.'
title: Code And Run
params:
  isoCode: it
  rtl: false
  description: Blog of a running developer
  displayName: IT
  dateFormat: 2 January 2006
  author:
    name: Code And Run
    image: avatar.png
    headline: Blog of a running developer
    bio: ""
    links:
      - email: mailto:alex@codeandrun.it
      - dev: https://dev.to/alexmufatti
      - github: https://github.com/alexmufatti
      - instagram: https://instagram.com/alexmufatti
      - linkedin: https://linkedin.com/in/amufatti
      - mastodon: https://mastodon.uno/@alexmufatti
      - reddit: https://reddit.com/user/alexmufatti
      - stack-overflow: https://stackoverflow.com/users/606622/alex-mufatti
      - twitter: https://twitter.com/alexmufatti
      - strava: https://www.strava.com/athletes/12353579
